## Loops

1. $\textbf {While} $ loops
2. $\textbf {For}   $ loops

In [92]:
n = 0
while n<10
    n = n+1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [93]:
myFriends

3-element Array{Any,1}:
 "Ram Krishna"
 "Shiva"
 "Sathya"

In [94]:
i = 1
while i<=length(myFriends)
    friend = myFriends[i]
    println("Hello $friend")
    i = i+1
end

Hello Ram Krishna
Hello Shiva
Hello Sathya


In [95]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [96]:
for n in 1:length(myFriends)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram Krishna
Hi, Shiva
Hi, Sathya


_In place of **'in'** in above loop we can also use **'='** or **'$\in$'**_

In [65]:
for n = 1:length(myFriends)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram Krishna
Hi, Shiva
Hi, Sathya


In [98]:
for n ∈ 1:length(myFriends) # for '∈' symbol type (\in + tab key)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram Krishna
Hi, Shiva
Hi, Sathya


In [100]:
m,n = 5,5
A = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [101]:
for i ∈ 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [102]:
B = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [103]:
for i in 1:m, j in 1:n
    B[i,j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

_More Julian way to create the above matrix is through **Array Comprehension**_

In [105]:
C = [i + j for i in 1:m,j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [108]:
for n in 1:10
    A = [i+j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

## Condtionals

In [110]:
x = 10
y = 20;

In [112]:
if x>y
    println("x value $x is greater than y value $y")
elseif x<y
    println("x value $x is lesser than y value $y")
else
    print("Both x and y are equal")
end

x value 10 is lesser than y value 20


**_If we want to just return the largest of two numbers_**

In [113]:
if x>y
    x
else
    y
end

20

**_The above can also be accomplished by using a ternary operator as below_**

In [115]:
(x>y) ? x : y

20

A fun related trick is short circuit evaluation with the syntax <br>
$\textbf {a && b}$

In [122]:
(x>y) && println("x is greater than y")

false

In [123]:
(x>y) && println("x is greater than y");

In [124]:
(x<y) && println("y is greater than x");

y is greater than x


## Functions

How to declare a function

In [126]:
function sayhi(name)
    println("Hello $name, it's great to see you")
end

sayhi (generic function with 1 method)

In [127]:
sayhi("Manideep")

Hello Manideep, it's great to see you


In [130]:
function square(num)
    num^2
end

square (generic function with 1 method)

In [131]:
square(3)

9

Alternatively, we can declare it in single line only

In [132]:
sayhi2(name) = println("Hello $name, great to see you !")

sayhi2 (generic function with 1 method)

In [133]:
sayhi2("Manideep")

Hello Manideep, great to see you !


In [134]:
square2(num) = num^2

square2 (generic function with 1 method)

In [135]:
square2(4)

16

Finally, we could have declared it as a anonymous function

In [137]:
sayhi3 = name -> println("Hello $name, glad to see you")

#9 (generic function with 1 method)

In [138]:
sayhi3("Manideep")

Hello Manideep, glad to see you


In [139]:
square3 = num -> num^2

#11 (generic function with 1 method)

In [140]:
square3(5)

25

## Duck typing in Julia

In [141]:
sayhi(1234)

Hello 1234, it's great to see you


In [142]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.264588  0.191155  0.401194
 0.146428  0.753463  0.583869
 0.732074  0.242587  0.391069

In [143]:
square(A)

3×3 Array{Float64,2}:
 0.391701  0.29193   0.374655
 0.576507  0.737337  0.727004
 0.515511  0.417588  0.588278

square function will not work on vector

In [144]:
B = rand(3)

3-element Array{Float64,1}:
 0.8216262068269662
 0.3828861114042692
 0.24340616989152708

In [145]:
square(B)

LoadError: MethodError: no method matching ^(::Array{Float64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::Integer) at mathconstants.jl:91
  ^(!Matched::Irrational{:ℯ}, ::Number) at mathconstants.jl:91
  ^(!Matched::BigInt, ::Integer) at gmp.jl:602
  ...

## Mutating Vs Non-Mutating Functions <br>

**Mutating** - Which returns the modified version of a value <br>
**Non-Mutating** - Which doesn't alter the version of a value

In [147]:
v = [3,5,4]

3-element Array{Int64,1}:
 3
 5
 4

In [148]:
sort(v)

3-element Array{Int64,1}:
 3
 4
 5

In [149]:
v

3-element Array{Int64,1}:
 3
 5
 4

In [150]:
sort!(v)

3-element Array{Int64,1}:
 3
 4
 5

In [151]:
v

3-element Array{Int64,1}:
 3
 4
 5

## Broadcasting

In [154]:
A = [i + 3j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [155]:
square(A)

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

In [156]:
square.(A)

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

In [157]:
v = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [158]:
square(v)

LoadError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::Integer) at mathconstants.jl:91
  ^(!Matched::Irrational{:ℯ}, ::Number) at mathconstants.jl:91
  ^(!Matched::BigInt, ::Integer) at gmp.jl:602
  ...

In [159]:
square.(v)

3-element Array{Int64,1}:
 1
 4
 9