# Julia-2 🤝

**Title :** $\text{Control Flow}$\
**Author :** $\textit{Manideep Bangaru}$ 👨🏻‍💻

$\small \text{on 11/12/2020}$

# Loops

1. $\textbf {While} $ loops
2. $\textbf {For}   $ loops

In [14]:
n = 0
while n<10
    global n = n+1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [21]:
myFriends = ["Ram","Shiva","Sathya"]

3-element Array{String,1}:
 "Ram"
 "Shiva"
 "Sathya"

In [26]:
i = 1
while i<=length(myFriends)
    friend = myFriends[i]
    println("Hello $friend")
    global i = i+1
end

Hello Ram
Hello Shiva
Hello Sathya


In [27]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [28]:
for n in 1:length(myFriends)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram
Hi, Shiva
Hi, Sathya


_In place of **'in'** in above loop we can also use **'='** or **'$\in$'**_

In [34]:
for n = 1:length(myFriends)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram
Hi, Shiva
Hi, Sathya


In [35]:
for n ∈ 1:length(myFriends) # for '∈' symbol type (\in + tab key)
    fri = myFriends[n]
    println("Hi, $fri")
end

Hi, Ram
Hi, Shiva
Hi, Sathya


In [36]:
m,n = 5,5
A = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [37]:
for i ∈ 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [38]:
B = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [39]:
for i in 1:m, j in 1:n
    B[i,j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

_More Julian way to create the above matrix is through **Array Comprehension**_

In [40]:
C = [i + j for i in 1:m,j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [41]:
for n in 1:10
    A = [i+j for i in 1:n, j in 1:n]
    #println(A)
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

## Condtionals

In [42]:
x = 10
y = 20;

In [43]:
if x>y
    println("x value $x is greater than y value $y")
elseif x<y
    println("x value $x is lesser than y value $y")
else
    print("Both x and y are equal")
end

x value 10 is lesser than y value 20


**_If we want to just return the largest of two numbers_**

In [44]:
if x>y
    x
else
    y
end

20

**_The above can also be accomplished by using a ternary operator as below_**

In [45]:
(x>y) ? x : y

20

A fun related trick is short circuit evaluation with the syntax <br>
$\textbf {a && b}$

In [46]:
(x>y) && println("x is greater than y")

false

In [47]:
(x>y) && println("x is greater than y");

In [48]:
(x<y) && println("y is greater than x");

y is greater than x


## Functions

How to declare a function

In [49]:
function sayhi(name)
    println("Hello $name, it's great to see you")
end

sayhi (generic function with 1 method)

In [50]:
sayhi("Manideep")

Hello Manideep, it's great to see you


In [51]:
function square(num)
    num^2
end

square (generic function with 1 method)

In [52]:
square(3)

9

One of the advantage of Julia is seen here, by defining two functions with the same names, it dynamically selects whichever is convenient for it

In [25]:
function square(num::String)
    println(num * num)
end

square (generic function with 2 methods)

In [26]:
square("Hi")

HiHi


Alternatively, we can declare it in single line only

In [27]:
sayhi2(name) = println("Hello $name, great to see you !")

sayhi2 (generic function with 1 method)

In [28]:
sayhi2("Manideep")

Hello Manideep, great to see you !


In [29]:
square2(num) = num^2

square2 (generic function with 1 method)

In [30]:
square2(4)

16

Finally, we could have declared it as a anonymous function

In [31]:
sayhi3 = name -> println("Hello $name, glad to see you")

#5 (generic function with 1 method)

In [32]:
sayhi3("Manideep")

Hello Manideep, glad to see you


In [33]:
square3 = num -> num^2

#7 (generic function with 1 method)

In [40]:
square3(5)

25

## Duck typing in Julia

In [41]:
sayhi(1234)

Hello 1234, it's great to see you


In [42]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.576042   0.536203  0.342745
 0.0456365  0.228045  0.722877
 0.654745   0.307616  0.844466

In [43]:
square(A)

3×3 Array{Float64,2}:
 0.580705  0.536588  0.874481
 0.509995  0.298844  0.790935
 0.944109  0.680998  1.1599

square function will not work on vector

In [44]:
B = rand(3)

3-element Array{Float64,1}:
 0.9495682917267698
 0.40155837141367234
 0.7039942415224707

In [45]:
square(B)

LoadError: MethodError: no method matching ^(::Array{Float64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::Integer) at mathconstants.jl:91
  ^(!Matched::Irrational{:ℯ}, ::Number) at mathconstants.jl:91
  ^(!Matched::BigInt, ::Integer) at gmp.jl:602
  ...

## Mutating Vs Non-Mutating Functions <br>

**Mutating** - Which returns the modified version of a value <br>
**Non-Mutating** - Which doesn't alter the version of a value

In [46]:
v = [3,5,4]

3-element Array{Int64,1}:
 3
 5
 4

In [47]:
sort(v)

3-element Array{Int64,1}:
 3
 4
 5

In [48]:
v

3-element Array{Int64,1}:
 3
 5
 4

In [49]:
sort!(v)

3-element Array{Int64,1}:
 3
 4
 5

In [50]:
v

3-element Array{Int64,1}:
 3
 4
 5

In [51]:
sort!(v,rev=true)

3-element Array{Int64,1}:
 5
 4
 3

In [52]:
v

3-element Array{Int64,1}:
 5
 4
 3

## Broadcasting

In [58]:
A = [i + 3j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [59]:
square(A)

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

In [60]:
square.(A)

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

In [53]:
v = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [54]:
square(v)

MethodError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:885
  ^(!Matched::Regex, ::Integer) at regex.jl:712
  ^(!Matched::Missing, ::Integer) at missing.jl:155
  ...

In [55]:
square.(v)

3-element Array{Int64,1}:
 1
 4
 9